### ISSUE TITLE
error code 500 Internal Error when Adding CryptoCurrency in CAS

### ISSUE THREAD

**Issue by wvabitpal** [GENERALBYTESCOM/batm_public#184]
@rpanak-generalbytes 
I am trying to add our cryptocurrency in CAS but since I upgraded to latest version (20190314), I can no longer add or edit , response 500 internal error.
![error500addcrypto](https://user-images.githubusercontent.com/48344788/54410963-8957b000-4728-11e9-845b-2abb915da7de.png)

**Comment by generalbytes** [comment]
Fixed by PR. Try server release 20190315.

**Comment by wvabitpal** [comment]
Hi @generalbytes the error is still here. I badly need it. Please fix it.
Attached is the admin error log.
![Screenshot_2019-03-18 GB CAS GENERAL BYTES - Crypto Application Server(1)](https://user-images.githubusercontent.com/48344788/54500658-edad8600-4959-11e9-88ee-904c8c8f9bcd.png)

**Comment by rpanak-generalbytes** [comment]
See the response in #186
